### ISSUE TITLE
exporting to blender does not work

### ISSUE THREAD

**Issue by sanya-2005** [RodZill4/material-maker#401] opened 2021-12-24 11:22 UTC
**Material Maker version:**
174bd84d944bb16edd6a92ac57fa939653cc5a93

**OS/device including version:**
ubuntu 20.04
geforce mx230

**Issue description:**
this is how the material looks in material maker
![Screenshot_20211224_141440](https://user-images.githubusercontent.com/88460753/147348408-3f2aa802-3a19-4bf8-9feb-c5173c30cc26.png)
and this is how in blender
![Screenshot_20211224_141515](https://user-images.githubusercontent.com/88460753/147348470-f02daaf8-5b75-4bad-b19f-c7b42dd3a61d.png)
I think the trouble is in exporting exr files, because this problem can be circumvented if each texture is manually pulled out of preview2d into png format

**Comment by Calinou** [comment] 2021-12-24 18:11
> I think the trouble is in exporting exr files,

In this case, this issue is a duplicate of https://github.com/RodZill4/material-maker/issues/372 and https://github.com/RodZill4/material-maker/issues/338.

**Comment by RodZill4** [comment] 2022-05-26 05:06
This should be fixed in 0.99 since MM now exports png files for non-greyscale channels.

**Closed by RodZill4** 2022-05-26 05:06 UTC
Labels: bug
